jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.default.url=jdbc:mysql://db:3306/test_docker_q1_0_2025_db?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
jdbc.default.username=test_docker_q1_0_2025_user
jdbc.default.password=test_docker_q1_0_2025_user

setup.wizard.enabled=false