spring.config.import=\
    classpath:/application-default.properties,\
    optional:configtree:${LIFERAY_ROUTES_CLIENT_EXTENSION}/,\
    optional:configtree:${LIFERAY_ROUTES_DXP}/

liferay.base-url=http://liferay:8080
liferay.registration-request-path=/o/c/registrationrequests

com.liferay.lxc.dxp.server.protocol=http
com.liferay.lxc.dxp.mainDomain=liferay:8080
com.liferay.lxc.dxp.domains=liferay:8080