spring.config.import=\
    classpath:/application-default.properties,\
    optional:configtree:${LIFERAY_ROUTES_CLIENT_EXTENSION}/,\
    optional:configtree:${LIFERAY_ROUTES_DXP}/

liferay.base-url=http://localhost:8080
liferay.registration-request-path=/o/c/registrationrequests

com.liferay.lxc.dxp.server.protocol=http
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.domains=localhost:8080

registration-create-user-oahs.oauth2.headless.server.client.id=id-47bf6a95-2267-7788-8fbf-278b419cde
registration-create-user-oahs.oauth2.headless.server.client.secret=secret-83fda8b9-ec8d-51c5-4509-f1f733f3a2
registration-create-user-oahs.oauth2.token.uri=/o/oauth2/token